name: Continuous Integration

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Jest
        run: npm test
